STATE_DEFAULT = 0
STATE_VIEWED = 1
STATE_FAILED = 2
STATE_SUCCESS = 3

STATES = (
    (STATE_DEFAULT, "DEFAULT"),
    (STATE_VIEWED, "VIEWED"),
    (STATE_FAILED, "FAILED"),
    (STATE_SUCCESS, "SUCCESS")
)

CONTENT_IMAGE = 0
CONTENT_AUDIO = 1

CONTENT_TYPES = (
    (CONTENT_IMAGE, "IMAGE"),
    (CONTENT_AUDIO, "AUDIO")
)
